feat(index): index api
bangumi/server pull request #104
Opened 2022-01-24 09:25 UTC by Sociosarbis

<details>
<summary> 获取目录信息 </summary>

GET `/v0/indices/{index_id}`

响应:

```JSON
{
  "id": 15045,
  "title": "日本动画最高收视率TOP100",
  "desc": "[url]http://www.tudou.com/programs/view/W6eIoxnHs6g/[/url]\r\n有美国动画混入，所以准确的说是在日本播放的动画最高收视率（而且是关东地区的\r\n基本大部分是70年代的，那个年代娱乐贫乏优势真大",
  "total": 101,
  "stat": {
    "comments": 8,
    "collects": 96
  },
  "created_at": "2012-11-08T09:23:16+00:00",
  "creator": {
    "username": "14127",
    "nickname": "nickname 14127"
  },
  "ban": false
}
```

</details>

close #

<details>
<summary> 获取目录条目 </summary>

GET `/v0/indices/{index_id}/subjects`

request parameters:
type: int
limit: int
offset: int

响应:

```JSON
{
  "total": 101,
  "limit": 30,
  "offset": 0,
  "data": [{
  "id": 32585,
  "type": 2,
  "name": "",
  "images": null,
  "infobox": null,
  "date": "2022-01-24",
  "comment": "3位 39.4",
  "added_at": "2012-11-08T13: 47: 24+00: 00"
}]
}
```

</details>

close #

2022-01-24 09:30 UTC, Trim21 commented
评论API先等等吧，社区相关的API都还没决定怎么响应

2022-01-31 11:10 UTC, Trim21 requested changes

2022-01-31 15:23 UTC, Sociosarbis commented on pol/services/index_service.py
> +        results = cast(
这里是为了编辑器有类型提示好看些😂

2022-01-31 15:24 UTC, Sociosarbis commented on pol/db/tables.py
> +        List["ChiiIndexComments"],
这类注释感觉是绕不开类型检查时才用的

2022-01-31 15:27 UTC, Sociosarbis commented on pol/services/index_service.py
> +        if subject_type:
我个人觉得这个`api`是已知`index_id`取其包含的`subject_id`，主体不是`subject`

2022-01-31 15:28 UTC, Trim21 commented on pol/db/tables.py
> +        List["ChiiIndexComments"],
`replies: List["ChiiIndexComments"] = relationship() # type: ignore` 跟这个效果是一样的…

2022-01-31 15:34 UTC, Trim21 commented on pol/services/index_service.py
> +        results = cast(
```python
results: Iterator[ChiiIndexRelated] = await self._db.scalars(
```

2022-01-31 15:59 UTC, Sociosarbis commented on pol/services/index_service.py
> +        results = cast(
![image](https://user-images.githubusercontent.com/25837029/151827869-46531389-c720-4af4-8d2e-3534afbaa484.png)
vscode提示的类型不对，如果那样写，下面的属性显示也是白色的

2022-01-31 16:27 UTC, Trim21 commented on pol/services/index_service.py
> +        results = cast(
怪事， vscode都支持pydantic的`BaseModel`反而不支持type hint

2022-01-31 16:38 UTC, Trim21 commented on pol/services/index_service.py
> +        results = cast(
这应该是个vscode的bug，List的话在下面的循环里能正确提示中间变量的类型。

2022-02-07 13:52 UTC, Trim21 requested changes

2022-02-07 13:55 UTC, Trim21 commented on pol/api/v0/index.py
> +                infobox=s.infobox,
这个 `infobox` 有点多余吧，感觉换成 `name_cn` 比较好

2022-02-07 14:01 UTC, Sociosarbis commented on pol/api/v0/index.py
> +                infobox=s.infobox,
![image](https://user-images.githubusercontent.com/25837029/152802354-54d0346a-ca9e-4752-879b-85863e2f7ffd.png)
这里是想给出红色圈的信息

2022-02-07 14:06 UTC, Trim21 commented on pol/api/v0/models/index.py
> +            images = subject_images(images)
在 `subject_images` 内处理了 image 为空的情况了

2022-02-10 03:29 UTC, Sociosarbis commented on pol/api/v0/models/index.py
> +        if type(images) == str:
因为这里不用考虑它是否有继承`str`，只是明确地表明希望是一个字符串，我理解是这样~~~

2022-02-10 03:44 UTC, Trim21 commented on pol/api/v0/models/index.py
> +        if type(images) == str:
我感觉用isinstance比较好吧？

2022-02-10 03:46 UTC, Sociosarbis commented on pol/api/v0/models/index.py
> +        if type(images) == str:
我觉得都可以，用isinstance就看起来会舒服些，那我改下。

2022-02-10 05:19 UTC, merged