feat(revision): rewrite person
bangumi/server pull request #127
Opened 2022-03-16 15:50 UTC by Sociosarbis

rewrite revision person history in go.

issues: #121

2022-03-16 15:54 UTC, Trim21 commented on domain/revision.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
为啥这copyright写的还是我，应该写你自己啊

2022-03-16 16:03 UTC, Trim21 commented on internal/test/web.go
> +				ret := map[uint32]model.User{}
```suggestion
				var ret = make(map[uint32]model.User{}, len(ids))
```

2022-03-16 16:06 UTC, Trim21 commented on revision/mysql_repository.go
> +	return mysqlRepo{
虽然没啥区别，但是感觉一行好看点

2022-03-16 16:08 UTC, Trim21 commented on web/handler/page.go
> +	if int64(q.Offset) >= count {
这又重复写了一遍...

2022-03-16 16:09 UTC, Trim21 commented on domain/revision.go
> +	) ([]*model.Revision, error)
别的返回的都是 `[]struct{}` ，统一一下吧

2022-03-16 16:12 UTC, Trim21 commented on web/util/http_cache.go
> +func CacheControl(c *fiber.Ctx, seconds int) {
这个先不用了吧

2022-03-16 16:13 UTC, Trim21 commented on web/res/revision.go
> +	Data      dao.GzipPhpSerializedBlob `json:"data"`
我的意思是这个Data具体的类型能不能写一下

2022-03-16 16:32 UTC, Trim21 commented on internal/cmd/gen/gorm.go
> +		gen.FieldType("rev_text", "GzipPhpSerializedBlob")),
我觉得这个放在repo里面处理比较好一些

2022-03-17 16:01 UTC, Trim21 commented on domain/revision.go
> +// Copyright (c) 2022 Sociosarbis <136657577@qq.com>
不是，为什么你把我的名字给删了。。。

2022-03-17 16:02 UTC, Trim21 commented on domain/revision.go
> +// Copyright (c) 2022 Sociosarbis <136657577@qq.com>
```suggestion
// Copyright (c) 2022 Sociosarbis <136657577@qq.com>
// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```

2022-03-17 16:51 UTC, Trim21 commented
`http://127.0.0.1:3000/v0/revisions/persons/8`

```json
{
  "created_at": "2011-01-28T03:08:00+08:00",
  "data": null,
  "creator": {
    "username": "",
    "nickname": ""
  },
  "summary": "新条目",
  "id": 8,
  "type": 3
}
```

2022-03-17 17:01 UTC, Trim21 commented
我看了一眼现在的数据，`Extra` 应该只有 `img` 一个字段是 `string` 类型。
`profession` 的 key 是7 种职业。这个就不用map了吧

2022-03-18 16:26 UTC, Trim21 requested changes

2022-03-18 16:26 UTC, Trim21 commented on revision/mysql_repository_test.go
> +	if data, ok := data["348475"]; ok {
```
	data, ok := data["348475"]
	require.True(t, ok)
	require.Equal(t, data.Name, "森岡浩之")
```

2022-03-18 16:26 UTC, Trim21 commented on revision/service.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-18 16:26 UTC, Trim21 commented on web/handler/revision.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-18 16:26 UTC, Trim21 commented on web/handler/revision_test.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-18 16:26 UTC, Trim21 commented on web/res/revision.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-19 17:27 UTC, Trim21 commented on domain/revision.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-19 17:29 UTC, Trim21 commented on model/revision.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-19 17:29 UTC, Trim21 commented on model/revision.type.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-19 17:30 UTC, Trim21 commented on revision/mysql_repository.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-19 17:31 UTC, Trim21 commented on revision/mysql_repository.go
> +	return mysqlRepo{q, log}, nil
```suggestion
	return mysqlRepo{q, log.Named("revision.mysqlRepo")}, nil
```

2022-03-19 17:41 UTC, Trim21 commented on revision/mysql_repository_test.go
> +// Copyright (c) 2022 Trim21 <trim21.me@gmail.com>
```suggestion
```

2022-03-19 17:44 UTC, Trim21 commented on web/handler/revision.go
> +		return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("bad query args: %s", err.Error()))
```suggestion
		return err
```

2022-03-19 17:48 UTC, Trim21 commented on web/handler/revision.go
> +		return fiber.NewError(fiber.StatusNotFound)
```suggestion
		return fiber.ErrNotFound
```

2022-03-19 17:48 UTC, Trim21 commented on web/handler/revision.go
> +		return errgo.Wrap(err, "user.GetByIDS")
```suggestion
		return errgo.Wrap(err, "user.GetByIDs")
```

2022-03-20 08:10 UTC, Trim21 requested changes
typo

2022-03-20 12:03 UTC, Sociosarbis commented on web/res/revision.go
> +		if m, ok := res.(map[string]interface{}); ok {
旧实现忘删了😄

2022-03-20 13:15 UTC, Trim21 commented on revision/mysql_repository_test.go
> +	if data, ok := data["348475"]; ok {
.

2022-03-20 13:54 UTC, merged