feat(revisions): API: character
bangumi/server pull request #135
Opened 2022-04-02 04:51 UTC by TWT233

这是一个 draft pull request

我可以实现 /v0/revisions/characters，现在是否有其他人在做相关工作？

accosiated: #121

2022-04-02 04:54 UTC, Trim21 commented
应该没有




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月2日(星期六) 中午12:52
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: [bangumi/server] feat(revisions): API: character (PR #135)




这是一个 draft pull request
 
我可以实现 /v0/revisions/characters，现在是否有其他人在做相关工作？
 
accosiated: #121
 
 
You can view, comment on, or merge this pull request online at:
 
&nbsp; https://github.com/bangumi/server/pull/135
 
Commit Summary
    
5fe64b8  placeholder
  
File Changes 
 
(6 files)
    
     M     .gitignore     (2)   
   
     M     domain/revision.go     (8)   
   
     M     go.mod     (3)   
   
     M     mocks/RevisionRepo.go     (123)   
   
     M     model/revision.type.go     (10)   
   
     M     revision/mysql_repository.go     (51)   
  
Patch Links:
    
https://github.com/bangumi/server/pull/135.patch
   
https://github.com/bangumi/server/pull/135.diff
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

2022-04-02 06:57 UTC, Trim21 commented on .gitignore
>  coverage.out
这没必要吧

2022-04-02 07:03 UTC, Trim21 commented
ci挂了，mock好像不太对？

2022-04-02 07:35 UTC, TWT233 commented on .gitignore
>  coverage.out
这边是ide自己修的，说dup了，之后我排除一下

2022-04-02 07:55 UTC, TWT233 commented
> ci没过，mock好像不太对？用`make mocks`重新生成下试试

fixed，前面是我手动用mockery cli生成的，交draft没细看

lint看起来是上游action出问题了

2022-04-02 08:46 UTC, Trim21 commented
似乎是setup-go 的bug

```
Setup go version spec ^1.17.8
Found in cache @ /opt/hostedtoolcache/go/1.18.0/x64
Added go to the path
Successfully setup go version ^1.17.8
go version go1.18 linux/amd64
```

2022-04-02 08:49 UTC, Trim21 commented
lint好了

2022-04-02 08:57 UTC, TWT233 commented
rebase了，我试试

On Apr 2, 2022, at 16:49, Trim21 ***@***.******@***.***>> wrote:



lint好了

—
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1086593464>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFCZO62VCDXZ3KGMTJ3VDAC3BANCNFSM5SKMCDUQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-02 17:35 UTC, Trim21 commented on web/res/revision.go
> +	Data      map[string]PersonRevisionDataItem `json:"data"`
人物和角色的版本可能不太一样，得看一下目前数据库里的实际内容

2022-04-06 02:19 UTC, TWT233 commented
我看SQL里人物和角色是同一个scheme用不同type区分，实际上字段也有区别的吗

On Apr 3, 2022, at 01:35, Trim21 ***@***.******@***.***>> wrote:



@Trim21 commented on this pull request.

________________________________

In web/res/revision.go<https://github.com/bangumi/server/pull/135#discussion_r841100463>:

> @@ -50,3 +50,12 @@ type PersonRevision struct {
        ID        uint32                            `json:"id"`
        Type      uint8                             `json:"type"`
 }
+
+type CharacterRevision struct {
+       CreatedAt time.Time                         `json:"created_at"`
+       Data      map[string]PersonRevisionDataItem `json:"data"`


人物和角色的版本可能不太一样，得看一下目前数据库里的实际内容

—
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#pullrequestreview-929590051>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFFZAZMV6TM4JZET4YTVDCANRANCNFSM5SKMCDUQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-06 02:22 UTC, Trim21 commented
现在的编辑版本实际内容是存在 `RevisionText` 表里的，这个表里的内容是 gzip+phpserlize 之后的 bytes

2022-04-06 02:23 UTC, Trim21 commented
`RevisionHistory` 只是个指向 `RevisionText` 的指针

2022-04-06 02:27 UTC, TWT233 commented on web/res/revision.go
> +	Data      map[string]PersonRevisionDataItem `json:"data"`
我看了下这段是自动生成的，的确不能用PersonRevisionDataItem，就算出于可读性这里也应该改掉

2022-04-06 02:35 UTC, TWT233 commented
> 现在的编辑版本实际内容是存在 `RevisionText` 表里的，这个表里的内容是 gzip+phpserlize 之后的 bytes。不同的 type 序列化了不同的对象。

好的，那我稍后试试

2022-04-06 11:10 UTC, TWT233 commented
> 现在的编辑版本实际内容是存在 `RevisionText` 表里的，这个表里的内容是 gzip+phpserlize 之后的 bytes。不同的 type 序列化了不同的对象。

对象结构在哪里有参考吗，我还没翻到这个

2022-04-06 11:15 UTC, Trim21 commented
从数据库里找一个数据的数据反序列化一下看看

2022-04-06 11:18 UTC, TWT233 commented
我看 character revision types 还挺多的，都一样的吗（有点不想每个都 unmarshal 一遍看）

2022-04-06 11:40 UTC, Trim21 commented
不用的type对应不一样的数据应该是

2022-04-06 11:40 UTC, Trim21 commented
python分支有python版本的unmarshal

2022-04-06 12:08 UTC, TWT233 commented
吼 我去看看

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Trim21 ***@***.***>
发送时间: Wednesday, April 6, 2022 7:41:02 PM
收件人: bangumi/server ***@***.***>
抄送: Housa Hitomi ***@***.***>; Author ***@***.***>
主题: Re: [bangumi/server] feat(revisions): API: character (PR #135)


python分支有python版本的unmarshal

―
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1090170633>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFCMGOKZMCMFG4T3QY3VDVZ45ANCNFSM5SKMCDUQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-09 08:32 UTC, TWT233 commented
done, 不过有个问题：我手动 unmarshal 了两个 type 的 rev text，发现结构差得有点多

先前实现的 person revision 也有这个问题，不过作者没有做这部分的处理

需要现在就做所有 types 的 rev text 解析吗

2022-04-09 08:42 UTC, Trim21 commented
起码加上主信息（infobox，简介）的那个type，其他的关联之类的随意。

2022-04-09 08:44 UTC, TWT233 commented
> 起码加上主信息（infobox，简介）的那个type，其他的关联之类的随意。

目前只加了这个主信息的 type：
https://github.com/bangumi/server/pull/135/files#diff-38275f398b73aa05fa11764cabd1ed70c923d2e6a324de1f15435ad07a84241cR66

2022-04-09 08:44 UTC, Trim21 requested changes

2022-04-09 08:44 UTC, Trim21 commented on web/res/revision.go
> +	InfoBox string `json:"crt_infobox"`
没必要加`crt_`这个前缀了吧

2022-04-09 08:46 UTC, TWT233 commented
表里捞出来的数据有这个前缀

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月9日 16:45
收件人: ***@***.***>
抄送: Housa ***@***.***>; ***@***.***>
主题: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)


@Trim21 requested changes on this pull request.


In web/res/revision.go<https://github.com/bangumi/server/pull/135#discussion_r846602202>:

> @@ -50,3 +51,19 @@ type PersonRevision struct {



        ID        uint32                            `json:"id"`



        Type      uint8                             `json:"type"`



 }



+



+type CharacterRevision struct {



+       CreatedAt time.Time                            `json:"created_at"`



+       Data      map[string]CharacterRevisionDataItem `json:"data"`



+       Creator   Creator                              `json:"creator"`



+       Summary   string                               `json:"summary"`



+       ID        uint32                               `json:"id"`



+       Type      uint8                                `json:"type"`



+}



+



+type CharacterRevisionDataItem struct {



+       Name    string `json:"crt_name"`



+       InfoBox string `json:"crt_infobox"`



没必要加crt_这个前缀了吧

―
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#pullrequestreview-937103869>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFD3ZQWKOZ5HNLFWET3VEE7RBANCNFSM5SKMCDUQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-09 08:51 UTC, Trim21 commented
那也没必要继续留着了吧...

2022-04-09 08:53 UTC, TWT233 commented on web/res/revision.go
> +	InfoBox string `json:"crt_infobox"`
应该还是要的，如果存储层不动的话

而且上面 person revision 的存储 key 也是有前缀的：
https://github.com/bangumi/server/pull/135/files/e6a6eb7d7fbcf781fa71086467f96c39a27c95b3#diff-38275f398b73aa05fa11764cabd1ed70c923d2e6a324de1f15435ad07a84241cR39

2022-04-09 08:54 UTC, Trim21 commented
person revision&nbsp;这个前缀也该删了




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月9日(星期六) 下午4:53
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)





 
@TWT233 commented on this pull request.
 
 
In web/res/revision.go:
 &gt; @@ -50,3 +51,19 @@ type PersonRevision struct {  	ID        uint32                            `json:"id"`  	Type      uint8                             `json:"type"`  } + +type CharacterRevision struct { +	CreatedAt time.Time                            `json:"created_at"` +	Data      map[string]CharacterRevisionDataItem `json:"data"` +	Creator   Creator                              `json:"creator"` +	Summary   string                               `json:"summary"` +	ID        uint32                               `json:"id"` +	Type      uint8                                `json:"type"` +} + +type CharacterRevisionDataItem struct { +	Name    string `json:"crt_name"` +	InfoBox string `json:"crt_infobox"`  
应该还是要的，如果存储层不动的话
 
而且上面 person revision 的存储 key 也是有前缀的：
 https://github.com/bangumi/server/pull/135/files/e6a6eb7d7fbcf781fa71086467f96c39a27c95b3#diff-38275f398b73aa05fa11764cabd1ed70c923d2e6a324de1f15435ad07a84241cR39
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-04-09 08:57 UTC, TWT233 commented
那就要迁移存储层了吧，我去删了跑测试看看

发件人: ***@***.***>
发送时间: 2022年4月9日 16:54
收件人: ***@***.***>
抄送: Housa ***@***.***>; ***@***.***>
主题: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)

person revision&nbsp;这个前缀也该删了




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: 2022年4月9日(星期六) 下午4:53
To: ***@***.***&gt;;
Cc: ***@***.***&gt;; ***@***.***&gt;;
Subject: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)






@TWT233 commented on this pull request.


In web/res/revision.go:
&gt; @@ -50,3 +51,19 @@ type PersonRevision struct { ID uint32 `json:"id"` Type uint8 `json:"type"` } + +type CharacterRevision struct { + CreatedAt time.Time `json:"created_at"` + Data map[string]CharacterRevisionDataItem `json:"data"` + Creator Creator `json:"creator"` + Summary string `json:"summary"` + ID uint32 `json:"id"` + Type uint8 `json:"type"` +} + +type CharacterRevisionDataItem struct { + Name string `json:"crt_name"` + InfoBox string `json:"crt_infobox"`
应该还是要的，如果存储层不动的话

而且上面 person revision 的存储 key 也是有前缀的：
https://github.com/bangumi/server/pull/135/files/e6a6eb7d7fbcf781fa71086467f96c39a27c95b3#diff-38275f398b73aa05fa11764cabd1ed70c923d2e6a324de1f15435ad07a84241cR39

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

―
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1093826718>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFCBSWE6FHDETRTTJTTVEFAV7ANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-09 08:59 UTC, Trim21 commented
这里不是单纯的web响应吗....

2022-04-09 08:59 UTC, Trim21 commented
点错了，不小心close了

2022-04-09 09:06 UTC, Trim21 commented
有具体类型的话也编辑一下`web/spec.yaml`

2022-04-09 09:14 UTC, TWT233 commented
> 这里不是单纯的web响应吗....

是的，搞混了，因为 unmarshal 也用到了这里的 tag

2022-04-09 09:15 UTC, Trim21 commented
我大概要先合另一个PR，可能会跟这个PR有冲突

2022-04-09 09:16 UTC, TWT233 commented
> 我大概要先合另一个PR，可能会跟这个PR有冲突

没问题

2022-04-09 09:47 UTC, TWT233 commented
rebased

2022-04-10 05:24 UTC, Trim21 commented on web/handler/revision_test.go
> +	if result, ok := r.Data.([]interface{})[0].(map[string]interface{}); ok {
这地方还是检查一下类型转换是否成功。

2022-04-10 05:25 UTC, Trim21 commented
我测试了一下 `http://127.0.0.1:3000/v0/revisions/characters?character_id=1`， 所有的data都是`null`

2022-04-10 05:29 UTC, Trim21 commented
`http://127.0.0.1:3000/v0/revisions/characters/1` 所有的 summary 都是空字符串，应该不太对吧...

2022-04-10 05:36 UTC, Trim21 commented
错误处理不太对，gorm 是有可能返回 `gorm.ErrRecordNotFound` 的，应该在 repo 里转成 `domain.ErrNotFound` ，而不是像现在这样直接返回原始的err，然后上层有err就直接返回Not Found了。

https://github.com/bangumi/server/blob/b9459649b1b177d9f5f37f236a2c574fa4ef841c/person/mysql_repository.go#L44-L47

（之前的PR也有一样的问题，我刚刚才发现）

2022-04-10 05:48 UTC, TWT233 commented
> 我测试了一下 `http://127.0.0.1:3000/v0/revisions/characters?character_id=1`， 所有的data都是`null`

好，我看看是哪里的问题

2022-04-10 10:34 UTC, Trim21 commented on domain/revision.go
> +	GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)
这里最好还是不要直接用 `model.Revision` 吧，刚看了下里面是个 `Data      interface{}` 这样感觉后面有点难维护。可能的话最好好事直接写出具体的类型来。

2022-04-10 10:35 UTC, Trim21 commented on domain/revision.go
> +	GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)
之前的 PR 里没注意到这个问题，现在这样感觉太难维护了...

2022-04-10 14:00 UTC, TWT233 commented on domain/revision.go
> +	GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)
这里的 `data ` 类型还有点多 抽个结构出来？

2022-04-10 22:06 UTC, Trim21 commented on domain/revision.go
> +	GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)
嗯

2022-04-11 16:12 UTC, Trim21 commented
能不能不要force push，每次都得从头review

2022-04-11 16:12 UTC, Trim21 commented
我合并的时候会squash，所以也不用在意commit message好看不好看。

2022-04-12 00:24 UTC, Trim21 commented on .gitignore
> +gen/
这是为啥

2022-04-12 00:24 UTC, Trim21 commented on domain/revision.go
> +	GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)
新加的这个方法只有这个PR里用到了吧，先改了这几个新方法的。旧的后面再改。

2022-04-12 00:31 UTC, Trim21 commented on revision/mysql_repository.go
> +	if err != nil {
这里的错误处理还是不太对，first这些方法会返回一个not found的error

2022-04-12 00:31 UTC, Trim21 commented on web/handler/revision_test.go
> +		if id, ok := result["id"].(float64); ok {
这地方的float64是json库反序列化的问题吗？

2022-04-12 00:31 UTC, Trim21 commented
我大概还是要先合另一个PR，会有冲突（）

2022-04-12 04:17 UTC, TWT233 commented
ok，我是平时上班用的 git 能看 diff between versions，就习惯了自己 squash

On Apr 12, 2022, at 00:12, Trim21 ***@***.******@***.***>> wrote:



能不能不要force push，每次都得从头review

—
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1095256171>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFEKCGEUXHVK6O5A6GLVERFNXANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-12 04:25 UTC, TWT233 commented
- 这里我还没改，待会儿我看看

- 是的，data 是 no scheme unmarshal

On Apr 12, 2022, at 08:31, Trim21 ***@***.******@***.***>> wrote:



@Trim21 commented on this pull request.

________________________________

In revision/mysql_repository.go<https://github.com/bangumi/server/pull/135#discussion_r847838959>:

> +
+func findRevisionText(datas []*dao.RevisionText, textID uint32) (*dao.RevisionText, bool) {
+       for _, data := range datas {
+               if data.TextID == textID {
+                       return data, true
+               }
+       }
+       return nil, false
+}
+
+func (r mysqlRepo) GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error) {
+       revision, err := r.q.RevisionHistory.WithContext(ctx).
+               Where(r.q.RevisionHistory.ID.Eq(id),
+                       r.q.RevisionHistory.Type.In(model.CharacterRevisionTypes()...)).
+               First()
+       if err != nil {


这里的错误处理还是不太对，first这些方法会返回一个not found的error

________________________________

In web/handler/revision_test.go<https://github.com/bangumi/server/pull/135#discussion_r847840439>:

> +     req := httptest.NewRequest(http.MethodGet, fmt.Sprintf("/v0/revisions/characters?character_id=%d", cid), http.NoBody)
+
+       resp, err := app.Test(req, -1)
+       require.NoError(t, err)
+       defer resp.Body.Close()
+
+       require.Equal(t, http.StatusOK, resp.StatusCode)
+
+       var r res.Paged
+
+       err = json.NewDecoder(resp.Body).Decode(&r)
+
+       require.NoError(t, err)
+
+       if result, ok := r.Data.([]interface{})[0].(map[string]interface{}); ok {
+               if id, ok := result["id"].(float64); ok {


这地方的float64是json库反序列化的问题吗？

—
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#pullrequestreview-938733816>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFAOMZXKRMZTJGJQONDVES75FANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-12 04:31 UTC, TWT233 commented on web/handler/revision_test.go
> +		if id, ok := result["id"].(float64); ok {
是的，data 是 no scheme unmarshal

2022-04-12 04:31 UTC, TWT233 commented on .gitignore
> +gen/
这个 gen 是 openapi 的生成文件

2022-04-12 11:26 UTC, TWT233 commented on domain/revision.go
> +	GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)
行

2022-04-15 03:19 UTC, Trim21 commented
有几个方法从handle挪到revision里去了。

2022-04-21 16:08 UTC, Trim21 commented
/ping

2022-04-21 17:12 UTC, TWT233 commented
这几天在打游戏（
预计这周末继续写

发件人: ***@***.***>
发送时间: 2022年4月22日 0:08
收件人: ***@***.***>
抄送: Housa ***@***.***>; ***@***.***>
主题: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)


/ping

―
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1105423401>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFD5VYQU6YAVJ6OSWY3VGF4O3ANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-23 08:11 UTC, TWT233 commented
done，这里的抽提结构的方法是分离model/revision里的metadata和data

做了一个`RevisionCommon`用来放meta，data放在`XXXRevisionData`中，用embed field来模拟sum type。为其他类型的数据留拓展性

@Trim21

2022-04-23 08:39 UTC, Trim21 commented
有冲突

2022-04-23 08:44 UTC, TWT233 commented
我 rebase 下

发件人: ***@***.***>
发送时间: 2022年4月23日 16:39
收件人: ***@***.***>
抄送: Housa ***@***.***>; ***@***.***>
主题: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)


有冲突

―
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1107434691>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFFKDAV45K4YWYYDTQ3VGOZLVANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-23 08:50 UTC, Trim21 commented
主要是go mod和新生成的文件的冲突，merge一下就行了

2022-04-23 13:46 UTC, Trim21 commented on revision/mysql_repository.go
> +	if err != nil {
（

2022-04-23 14:10 UTC, Trim21 requested changes

2022-04-23 14:10 UTC, Trim21 commented on web/handler/revision_test.go
> +	if result, ok := r.Data.([]interface{})[0].(map[string]interface{}); ok {
。

2022-04-23 14:10 UTC, Trim21 commented on web/handler/revision.go
> +	revCommons := make([]model.RevisionCommon, 0, len(revisions))
这地方为啥不直接用个slice把createID收集起来？这个 `revCommons` 也没有其他用处啊

2022-04-23 14:10 UTC, Trim21 commented on web/handler/revision.go
> +		return fiber.NewError(fiber.StatusBadRequest, fmt.Sprintf("bad param id: %s", c.Params("id")))
quote一下

2022-04-23 14:34 UTC, Trim21 requested changes

2022-04-23 14:34 UTC, Trim21 commented on revision/mysql_repository_test.go
> +	require.Equal(t, domain.ErrNotFound, err)
应该用`errors.Is`的

2022-04-23 16:53 UTC, Trim21 commented on revision/mysql_repository.go
> +	if err == nil {
/ping

2022-04-23 20:49 UTC, Trim21 commented
现在 http://127.0.0.1:3000/v0/revisions/characters?character_id=1 的响应更奇怪了...

2022-04-23 20:50 UTC, Trim21 commented
![image](https://user-images.githubusercontent.com/13553903/164945572-a210d221-592c-40f7-a87e-b42e81a2162f.png)
 
这些data都是完全相同的全部历史

2022-04-23 20:56 UTC, Trim21 commented
https://api.bgm.tv/v0/revisions/subjects?subject_id=1

```json
{
  "total": 3,
  "limit": 30,
  "offset": 0,
  "data": [
    {
      "id": 718391,
      "type": 1,
      "creator": {
        "username": "wataame",
        "nickname": "綿飴"
      },
      "summary": "信息转更早出版的台版：内容扩充（出版社、页数、价格）&amp;资讯更新（发售日、ISBN[勘误]）",
      "created_at": "2021-01-23T15:52:51+00:00"
    },
    {
      "id": 580329,
      "type": 1,
      "creator": {
        "username": "hurakan",
        "nickname": "🥵🥵🥵"
      },
      "summary": "内容扩充",
      "created_at": "2018-08-27T07:28:13+00:00"
    },
    {
      "id": 48260,
      "type": 1,
      "creator": {
        "username": "valn",
        "nickname": "v仔💎"
      },
      "summary": "",
      "created_at": "2011-12-05T03:47:13+00:00"
    }
  ]
}
```

2022-04-23 20:56 UTC, Trim21 commented
https://api.bgm.tv/v0/revisions/subjects/1

```json
{
  "id": 1,
  "type": 1,
  "creator": {
    "username": "sai",
    "nickname": "Sai🖖"
  },
  "summary": "维基化",
  "created_at": "2009-01-18T07:06:08+00:00",
  "data": {
    "subject_id": 499,
    "name": "文学少女",
    "name_cn": "",
    "vote_field": "",
    "type": 1,
    "type_id": 1,
    "field_infobox": "{{Infobox animanga/BookSeries\r\n|中文名= \r\n|作者= 野村美月\r\n|插图= 竹冈美穗\r\n|出版社= 尖端出版社\r\n|连载杂志= \r\n|发售日= \r\n|开始= \r\n|结束= \r\n|册数= \r\n|其他= \r\n}}",
    "field_summary": "文学少女系列（”文学少女”シリーズ）是小说家野村美月与插画家竹冈美穗所推出的轻小说，第一卷于2006年4月发售，在没有被动画化、漫画化的情况下仍在这本轻小说真厉害！2007中得到第八名，这本轻小说真厉害！2008中得到第三名。获得第一届Light Novel Award的Mystery部门大奖。台湾中文版由尖端出版社发行。",
    "field_eps": 0,
    "platform": 0
  }
}
```

2022-04-23 21:08 UTC, Trim21 commented
大概 `ListCharacterRelated` 不需要传 data 出来

2022-04-23 21:09 UTC, Trim21 commented on revision/mysql_repository.go
> +			return nil, errgo.Msg(errRevisionTextNotFound, fmt.Sprintf("textID: %d", revision.TextID))
`errRevisionTextNotFound` 没导出的话不需要包装错误，外面的调用者也没办法检查。

2022-04-24 02:57 UTC, TWT233 commented
> ![image](https://user-images.githubusercontent.com/13553903/164945572-a210d221-592c-40f7-a87e-b42e81a2162f.png)
> 
> 这些data都是完全相同的版本历史

在`chii_rev_history`里搜这几个id，他们的rev_text_id都是1，所以这个是符合预期的：

<img width="1466" alt="image" src="https://user-images.githubusercontent.com/11287700/164954219-96f5d244-132b-4363-961d-a0f12ba7ec8f.png">

2022-04-24 03:00 UTC, Trim21 commented
这个HTTP响应看着太难受了啊，一样的大object为什么要出现这么多次...



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月24日(星期天) 上午10:58
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)





  

 
这些data都是完全相同的版本历史
  
在chii_rev_history里搜这几个id，他们的rev_text_id都是1，所以这个是符合预期的：
 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-04-24 03:03 UTC, TWT233 commented
uhmm 因为数据就如此？毕竟不能破坏数据的正确性

要改的话只能看看这里是不是还有什么特殊过滤逻辑了，比如按着`created_at`抽`data`里面一段走...虽然我觉得不太可能

2022-04-24 03:04 UTC, Trim21 commented
这个 List*&nbsp;的方法不返回data，然后在这个响应的Data上加上 `omitempty`&nbsp;



------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月24日(星期天) 中午11:03
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [bangumi/server] feat(web): API: revisions/characters[/:id] (PR #135)





 
uhmm 因为数据就如此？毕竟不能破坏数据的正确性
 
要改的话只能看看这里是不是还有什么特殊过滤逻辑了，比如按着created_at抽data里面一段走...虽然我觉得不太可能
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2022-04-24 03:28 UTC, TWT233 commented
喔 这个接口只返回metadata？我去康康spec

2022-04-24 03:34 UTC, TWT233 commented
是的，这个接口不需要返回data，之前做错了

2022-04-24 03:37 UTC, TWT233 commented
忘了lint和test。。。我补一下

2022-04-24 04:31 UTC, TWT233 commented
fixed，同时也squash rebase到master上了

2022-04-24 11:33 UTC, Trim21 commented
邮件回复的markdown怎么全是转义…

2022-04-24 11:38 UTC, Trim21 commented
看着OK，等会测试下

2022-04-24 11:58 UTC, Trim21 commented on revision/mysql_repository.go
> +	if err != nil {
这里用log打个错误日志的，正常不应该有 `gorm.ErrRecordNotFound` 出现的

2022-04-24 12:18 UTC, Trim21 commented
啊，抱歉，不小心推错了- -

2022-04-24 12:20 UTC, Trim21 commented
类似于 https://github.com/bangumi/server/blob/4967ececaf1cd87511a2f5c3d032572c280d6eab/revision/mysql_repository.go#L94-L102

2022-04-24 12:59 UTC, TWT233 commented
done

2022-04-24 13:00 UTC, Trim21 commented on revision/mysql_repository.go
> +		return model.CharacterRevision{}, wrapGORMError(err)
```suggestion
		return model.CharacterRevision{}, errgo.Wrap(err, "dal")
```

2022-04-24 13:15 UTC, merged

2022-10-11 07:36 UTC, TWT233 commented
那要合在这个commit做吗，感觉下一个commit改比较好

On Apr 11, 2022, at 06:06, Trim21 ***@***.******@***.***>> wrote:



@Trim21 commented on this pull request.

________________________________

In domain/revision.go<https://github.com/bangumi/server/pull/135#discussion_r846849401>:

> @@ -38,4 +39,12 @@ type RevisionRepo interface {
        ) ([]model.Revision, error)

        GetSubjectRelated(ctx context.Context, id model.IDType) (model.Revision, error)
+
+       CountCharacterRelated(ctx context.Context, characterID model.CharacterIDType) (int64, error)
+
+       ListCharacterRelated(
+               ctx context.Context, characterID model.CharacterIDType, limit int, offset int,
+       ) ([]model.Revision, error)
+
+       GetCharacterRelated(ctx context.Context, id model.IDType) (model.Revision, error)


嗯

—
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#discussion_r846849401>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFF25WRCLKNHXGRR343VENGF3ANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-11 09:20 UTC, TWT233 commented
ok，我之后merge看看

On Apr 15, 2022, at 11:20, Trim21 ***@***.******@***.***>> wrote:



有几个方法从handle挪到revision里去了。

—
Reply to this email directly, view it on GitHub<https://github.com/bangumi/server/pull/135#issuecomment-1099813937>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACWDZFF3IWJBAVLGC4KPYILVFDN6NANCNFSM5SKMCDUQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-10-11 10:09 UTC, trim21 commented
啥？

2022-10-11 15:16 UTC, trim21 commented
GitHub或者Gmail好像突然出了点问题，把几个月前的邮件回拖到了现在才处理