目录直接相关的 API
bangumi/server pull request #234
Opened 2022-10-08 12:26 UTC by RanKKI

v0.Post("/indices", req.JSON, h.NeedLogin, h.NewIndex)
v0.Put("/indices/:id", req.JSON, h.NeedLogin, h.UpdateIndex)
v0.Delete("/indices/:id", h.NeedLogin, h.DeleteIndex)

v0.Post("/indices/:id/subjects", req.JSON, h.NeedLogin, h.AddIndexSubject)
v0.Put("/indices/:id/subjects/:subject_id", req.JSON, h.NeedLogin, h.UpdateIndexSubject)
v0.Delete("/indices/:id/subjects/:subject_id", h.NeedLogin, h.RemoveIndexSubject)

2022-10-08 12:28 UTC, trim21 commented on internal/web/res/index.go
> -	Description string        `json:"desc"`
这里改了的话会break change吧

2022-10-08 12:30 UTC, RanKKI commented on internal/web/res/index.go
> -	Description string        `json:"desc"`
确实... 但命名不统一好烦哦

2022-10-12 04:38 UTC, trim21 commented
这个PR是可以review了吗？改一下openapi文件？

2022-10-12 04:55 UTC, trim21 commented on internal/web/res/index.go
> +	UpdateAt    time.Time     `json:"update_at"`
```suggestion
	UpdatedAt    time.Time     `json:"updated_at"`
```

2022-10-12 05:14 UTC, RanKKI commented
> 这个PR是可以review了吗？改一下openapi文件？

不好意思，这两天在忙别的， 先 review 代码吧， openapi 我今天晚点补上

2022-10-12 05:52 UTC, trim21 commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) Delete(ctx context.Context, id model.IndexID) error {
还有用户收藏？

2022-10-12 06:01 UTC, trim21 commented on internal/index/mysql_repository_test.go
> +func TestMysqlRepo_UpdateIndex(t *testing.T) {
这个是不是加一个新目录用来测试比较好

2022-10-12 06:02 UTC, RanKKI commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) Delete(ctx context.Context, id model.IndexID) error {
这个是更新目录的标题和介绍和删除目录，我没理解错应该也是放这次的pr里 🤔

2022-10-12 06:02 UTC, trim21 commented on internal/model/index.go
> +	UpdateAt    time.Time
```suggestion
	UpdatedAt    time.Time
```

2022-10-12 06:03 UTC, RanKKI commented on internal/index/mysql_repository_test.go
> +func TestMysqlRepo_UpdateIndex(t *testing.T) {
确实应该新加个 or2

2022-10-12 06:06 UTC, trim21 commented on internal/web/handler.go
> +	v0.Delete("/indices/:id", h.NeedLogin, h.DeleteIndex)
```suggestion
```

这个暂时先等等吧

2022-10-12 07:05 UTC, RanKKI commented on internal/web/handler.go
> +	v0.Delete("/indices/:id", h.NeedLogin, h.DeleteIndex)
好，逻辑我就不删了， 就删路由

2022-10-12 11:37 UTC, trim21 commented on internal/web/handler/index.go
> -func (h Handler) RemoveIndexSubject(c *fiber.Ctx) error {
为啥这个被删了，删错了？

2022-10-12 11:41 UTC, trim21 commented on internal/web/handler/index.go
> -func (h Handler) RemoveIndexSubject(c *fiber.Ctx) error {
。。。build test和lint居然都没报错

2022-10-12 11:41 UTC, trim21 commented on internal/web/handler/index.go
> -func (h Handler) RemoveIndexSubject(c *fiber.Ctx) error {
。。哦你删错路由了

2022-10-12 11:47 UTC, RanKKI commented on internal/web/handler/index.go
> -func (h Handler) RemoveIndexSubject(c *fiber.Ctx) error {
我也好奇来着，然后发现我把配套设施也全干掉了.....

2022-10-12 11:52 UTC, trim21 commented
没理解错的话，条目已经在目录里的情况下，`PUT` 方法会报错？

2022-10-12 11:55 UTC, RanKKI commented
> 没理解错的话，条目已经在目录里的情况下，`PUT` 方法会报错？

为啥会报错呢？
但我发现错误处理没有做干净， put 的时候可能不存在，应该 404

2022-10-12 11:58 UTC, trim21 commented
啊，是的，说错了，应该是对应条目不存在的时候处理的不太对。

感觉可以直接把对应的条目添加到目录里

2022-10-12 11:58 UTC, trim21 commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) Delete(ctx context.Context, id model.IndexID) error {
这个还留着吗

2022-10-12 12:04 UTC, RanKKI commented
> 啊，是的，说错了，应该是对应条目不存在的时候处理的不太对。
> 
> 感觉可以直接把对应的条目添加到目录里

两种处理（指加进去和404）都能接受，但个人感觉还是报 404 合适点，put 感觉就是修改资源，post 是新增

2022-10-12 12:10 UTC, trim21 commented
这里既然put要传全部的数据，并且已知对应的url了，就直接添加吧

2022-10-12 12:10 UTC, trim21 commented
或者改成patch方法，然后报404

2022-10-12 12:11 UTC, RanKKI commented
嗯，好，我在 api 文档里也备注下

2022-10-13 02:31 UTC, RanKKI commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) Delete(ctx context.Context, id model.IndexID) error {
嗯，数据库操作留着的，只是删了路由 （毕竟以后还会用到

2022-10-13 18:12 UTC, trim21 commented on internal/index/mysql_repository.go
> +			Rid:      id,
重命名一下rid和sid吧，单看命名看不出来是什么

2022-10-14 00:36 UTC, RanKKI commented on internal/index/mysql_repository.go
> +			Rid:      id,
🤔 确实，写的时候十分诡异， 那我要改 gorm gen 的东西了， 顺便把 Dateline 也重命名下... 太奇怪的变量名了

2022-10-15 03:22 UTC, RanKKI commented
咨询一下，
```sql
CREATE TABLE
  IF NOT EXISTS `chii_index_related` (
    `idx_rlt_cat` TINYINT(3) NOT NULL,
    `idx_rlt_type` SMALLINT(6) UNSIGNED NOT NULL COMMENT '关联条目类型',
  ) ENGINE = MyISAM DEFAULT CHARSET = utf8 COMMENT = '目录关联表';
```

这里的 `cat` 我没理解错应该是 category，是目录里筛选条目类型的东西，但 `type` 是干这事的..
是弃用的字段么

2022-10-15 12:46 UTC, trim21 commented
看下slack私聊

2022-10-15 17:08 UTC, trim21 commented on internal/web/res/index.go
> +	UpdatedAt   time.Time     `json:"updated_at"`
这个没加到api spec里面吧？

2022-10-15 17:09 UTC, trim21 commented on openapi/v0.yaml
> +      parameters:
写一个公用的parameter跟其他方法复用吧

2022-10-15 17:27 UTC, trim21 requested changes

2022-10-15 17:27 UTC, trim21 commented on openapi/v0.yaml
> +        - required: true
这个有一个component可以直接用的

2022-10-15 17:27 UTC, trim21 commented on internal/web/handler/index.go
> +		return errgo.Wrap(err, "request data is invalid")
```suggestion
		return res.JSONError(c, err)
```

2022-10-15 17:27 UTC, trim21 commented on internal/web/handler/index.go
> +		Title:       reqData.Title,
感觉应该加个方法检查这些字符串输入的不可见字符

2022-10-15 17:27 UTC, trim21 commented on internal/web/handler/index.go
> +	id, err := req.ParseIndexID(c.Params("id"))
这个id改成调用者传进来吧

2022-10-15 17:27 UTC, trim21 commented on internal/web/handler/index.go
> +	// TODO: 是否走 redis 缓存
这要是用在修改路由里就不需要走redis缓存了

2022-10-15 17:27 UTC, trim21 commented on internal/web/handler/index.go
> +		return errgo.Wrap(err, "request data is invalid")
```suggestion
		return res.JSONError(c, err)
```

2022-10-15 17:27 UTC, trim21 commented on internal/web/handler/index.go
> +func modelToResponse(i *model.Index, u model.User) res.Index {
把目录相关的路由移到 handler/index 吧

2022-10-15 17:27 UTC, trim21 commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) AddOrUpdateIndexSubject(
这个是不是应该包在一个事务里

2022-10-15 17:50 UTC, trim21 commented
`subject.ConvertDao` 本来是没想导出的，ListSubjects应该在controller上面做的

2022-10-15 19:47 UTC, trim21 commented
> 咨询一下，
> 
> ```sql
> CREATE TABLE
>   IF NOT EXISTS `chii_index_related` (
>     `idx_rlt_cat` TINYINT(3) NOT NULL,
>     `idx_rlt_type` SMALLINT(6) UNSIGNED NOT NULL COMMENT '关联条目类型',
>   ) ENGINE = MyISAM DEFAULT CHARSET = utf8 COMMENT = '目录关联表';
> ```
> 
> 这里的 `cat` 我没理解错应该是 category，是目录里筛选条目类型的东西，但 `type` 是干这事的.. 是弃用的字段么

我猜这个type是条目类型，cat不知道是什么

2022-10-16 01:06 UTC, RanKKI commented on internal/web/handler/index.go
> +	// TODO: 是否走 redis 缓存
删除的时候，是不是要把 redis 里的缓存也删掉？

2022-10-16 01:16 UTC, RanKKI commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) AddOrUpdateIndexSubject(
不需要吧，前面都是查询， 后面要么改或者增，没必要用事务

但我觉得这要加锁，避免创建两份目录

2022-10-16 01:19 UTC, RanKKI commented
> 这个type是条目类型，cat不知道是什么，可能只是我们没用到。

我看了下代码，之前是用 cat 做的分类，没有见到过 type 字段。

昨天还发现一点问题， `ListSubjects` 接口的 `type`  不支持传入 `person` 和 `character` 两个值

2022-10-16 03:24 UTC, trim21 commented on internal/web/handler/index.go
> +	// TODO: 是否走 redis 缓存
修改目录的时候都就应该删除一下redis对应的缓存

2022-10-16 11:20 UTC, trim21 commented
> > 这个type是条目类型，cat不知道是什么，可能只是我们没用到。
> 
> 我看了下代码，之前是用 cat 做的分类，没有见到过 type 字段。
> 
> 昨天还发现一点问题， `ListSubjects` 接口的 `type` 不支持传入 `person` 和 `character` 两个值

我突然发现忘了做角色和人物的相关功能了

2022-10-17 03:51 UTC, RanKKI commented
我先把目录的补完吧， 
期末了要准备 Final 了，时间不是很多，结束如果没有人搞 我可以来整。

2022-10-17 05:02 UTC, RanKKI commented on internal/web/handler/index.go
> +func modelToResponse(i *model.Index, u model.User) res.Index {
是指 index 单独一个 package 么?  
( /index 是指目录吧..

2022-10-17 05:51 UTC, trim21 commented on internal/web/handler/index.go
> +func modelToResponse(i *model.Index, u model.User) res.Index {
是，类似现在的handler/user

2022-10-17 05:53 UTC, trim21 commented
> 我先把目录的补完吧， 期末了要准备 Final 了，时间不是很多，结束如果没有人搞 我可以来整。

OK

2022-10-17 05:53 UTC, trim21 commented
合并一下主线（

2022-10-17 14:55 UTC, RanKKI commented on internal/web/handler/index.go
> +	id, err := req.ParseIndexID(c.Params("id"))
不是很理解为啥要把 id 作为参数。

2022-10-17 15:05 UTC, trim21 commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) AddOrUpdateIndexSubject(
> 不需要吧，前面都是查询， 后面要么改或者增，没必要用事务
> 
> 但我觉得这要加锁，避免创建两份目录

同时发两个请求的话有可能添加两个条目进目录吧，或者因为有unique key（没看sql表怎么定义的）而出错

2022-10-17 15:07 UTC, trim21 commented on internal/web/handler/index.go
> +		Title:       reqData.Title,
https://github.com/bangumi/server/blob/7f6e36ac205da31a78e2351a2986a5cbf486cba8/internal/dam/dam_test.go#L32

2022-10-17 16:45 UTC, trim21 commented on internal/web/handler/index.go
> +		Title:       reqData.Title,
这个方法应该够用了，不可见字符和控制字符都过不去测试。

2022-10-18 01:27 UTC, RanKKI commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) AddOrUpdateIndexSubject(
嗯， 用事务也没法解决。
感觉对于这种创建资源的 还是应该是一定时间内阻止一样的请求 #233

2022-10-18 04:59 UTC, RanKKI commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) AddOrUpdateIndexSubject(
嗯🤔，加锁的话可以让第二个 `Add` 请求变成 `Update`，感觉不如直接 Drop 第二个请求

2022-10-21 10:38 UTC, trim21 commented
lint没过

2022-10-21 11:10 UTC, RanKKI commented
是 ctrl 里的一个lint， 我打算再开个pr修来着，毕竟和这次功能没啥关系..Hugh(Hui) LiuKind Regards On Oct 21, 2022, at 18:38, Trim21 ***@***.***> wrote:﻿
lint没过

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-21 12:29 UTC, trim21 commented
需要把 `func (ctrl Ctrl) GetIndexWithCache(c context.Context, id uint32) (res.Index, bool, error) {` 改成 `func (ctl Ctrl) GetIndexWithCache(c context.Context, id uint32) (res.Index, bool, error) {`

2022-10-21 12:30 UTC, trim21 commented
报错是报在了其他文件，但是是这个PR引起的

2022-10-22 03:13 UTC, RanKKI commented
> 报错是报在了其他文件，但是是这个PR引起的

发现了.. 我这报错在 `internal/ctrl/count_episode_for_subject.go:30:17:` 但是是因为 `index.go`... 
改好了。

2022-10-22 03:34 UTC, RanKKI commented on internal/index/mysql_repository.go
> +func (r mysqlRepo) AddOrUpdateIndexSubject(
这个要不我写个中间件 drop 请求吧.. 没啥别的好的想法解决这个问题了

2022-10-24 08:49 UTC, trim21 commented
sai老板还在摸，再等等（

2022-10-24 10:51 UTC, trim21 commented
sai老板给权限了（

和了一个别的PR，有个冲突

2022-10-24 11:34 UTC, trim21 commented on internal/index/mysql_repository.go
> +		FirstOrInit()
`FirstOrInit`还会返回`gorm.ErrRecordNotFound`吗?

2022-10-24 11:37 UTC, trim21 commented on internal/index/mysql_repository.go
> +		FirstOrInit()
而且这里``Init`了，`indexSubject.ID`还是0吗。

我记得相关的方法针对不存在的情况返回的都是一个`nil`，不会空指针吗

2022-10-24 11:51 UTC, RanKKI commented on internal/index/mysql_repository.go
> +		FirstOrInit()
> `FirstOrInit`还会返回`gorm.ErrRecordNotFound`吗?

不会，确实判断的有点多余了

> 而且这里`Init`了，`indexSubject.ID`还是0吗。

这里主要是初始化对象，使 `indexSubject` 不会是 nil， 然后里面的数据都是默认值， Int 默认就是 0

2022-10-24 12:58 UTC, trim21 commented on internal/index/mysql_repository.go
> +		FirstOrInit()
那下面convertDao失败的话岂不是会留一条错误纪录在里面...

2022-10-24 13:02 UTC, RanKKI commented on internal/index/mysql_repository.go
> +		FirstOrInit()
咦，convertDao 在 firstOrInit 上面呀。

如果 convert 失败了， 错误就直接出去了。

2022-10-24 13:06 UTC, trim21 commented on internal/index/mysql_repository.go
> +		FirstOrInit()
啊 确实，看错了

2022-10-24 13:53 UTC, merged