feat: add api index collect
bangumi/server pull request #314
Opened 2023-03-21 16:47 UTC by kagaya85

link #230 

implements:
- [x] 收藏目录 POST /indices/{index_id}/collect
- [x]  取消收藏 DELETE /indices/{index_id}/collect

2023-03-26 11:25 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
坏事，之前没有这个吗…

2023-03-26 11:27 UTC, trim21 commented on readme.md
> +git submodule update --init --recursive
不需要吧…？

2023-03-26 13:52 UTC, kagaya85 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
没有的，我也很奇怪

2023-03-26 13:54 UTC, kagaya85 commented on readme.md
> +git submodule update --init --recursive
嗯嗯，毕竟第一遍执行测试的话也会报错，写文档里的话可以提醒一下，如果不需要的话我就删了

2023-03-26 13:59 UTC, kagaya85 commented on web/handler/index/collect_test.go
> +	// mockIndex.EXPECT().DeleteIndexCollect(mock.Anything, uint32(322), uint32(6)).Return(nil)
这里如果mock `DeleteIndexCollect` 的话会报错：
```
The code you are testing needs to make 1 more call(s).
```
还在看是什么问题

2023-03-26 14:40 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
不需要

https://github.com/bangumi/server/blob/8c2dec63733d8c9d2fb16492914e8b2f4366b3c4/.github/workflows/test.yaml#L71

2023-03-26 14:50 UTC, trim21 commented on readme.md
> +git submodule update --init --recursive
不用啊？submodule里面都是proto文件，是用不到的

2023-03-26 14:52 UTC, trim21 commented on readme.md
> +git submodule update --init --recursive
哦这个是task gen的时候可能会用到这不是测试的时候会用到

2023-03-26 15:42 UTC, kagaya85 commented on readme.md
> +git submodule update --init --recursive
是/pkg/wiki/testdata目录下的，好像是wiki相关的

2023-03-26 15:49 UTC, kagaya85 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
可以加这个配置项，或者改一下tag里的env-default默认值，不然本地跑会有一些问题

2023-03-27 05:38 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
本地跑的时候放一个 .env 文件不就好了？

2023-03-27 05:41 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
```suggestion
```

2023-03-27 06:24 UTC, kagaya85 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
ok理解了，我以为文档里的env相关的设置描述是可选的，可以优化一下改成“建议”。
另外`env-default`的值还需要同时改成`redis://:redis-pass@127.0.0.1:6379/0`吗？，

2023-03-27 06:37 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
不改

2023-03-27 06:37 UTC, trim21 commented on readme.md
> +git submodule update --init --recursive
哦对，忘记了。

2023-03-27 06:38 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
env相关的设置描述是可选的啊，有什么问题吗...

2023-03-27 06:39 UTC, trim21 commented on readme.md
> +git submodule update --init --recursive
https://github.com/bangumi/server#init

你clone的时候没加`--recursive`吧...?

2023-03-27 06:41 UTC, kagaya85 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
> env相关的设置描述是可选的啊，有什么问题吗...

我理解的可选的意思是可以不需要该配置，运行dev-env后就可以跑起来，但现在是不行的，因为默认的`REDIS_URI`的环境变量是不带密码的

2023-03-27 06:49 UTC, kagaya85 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
这个不带默认值的uri是用在生产环境的吗？

2023-03-27 06:52 UTC, trim21 commented on config/config.go
> +	RedisPassword string `yaml:"redis_pass" env:"REDIS_PASS" env-default:"redis-pass"`
不是

2023-03-27 07:06 UTC, trim21 commented on internal/index/mysql_repository.go
> +		return nil, err
```suggestion
		return nil, errgo.Trace(err)
```

2023-03-27 07:07 UTC, trim21 commented on internal/index/mysql_repository_test.go
> +	err := repo.AddIndexCollect(ctx, 15465, 233)
这个测试没检查是否成功添加？

2023-03-27 07:08 UTC, trim21 commented on internal/search/noop.go
> +func (n NoopClient) OnSubjectUpdate(_ context.Context, _ model.SubjectID) error {
这些无关的文件就不要修改了吧

2023-03-27 07:08 UTC, kagaya85 commented on internal/search/noop.go
> +func (n NoopClient) OnSubjectUpdate(_ context.Context, _ model.SubjectID) error {
不改的话lint过不了

2023-03-27 07:09 UTC, kagaya85 commented on internal/index/mysql_repository_test.go
> +	err := repo.AddIndexCollect(ctx, 15465, 233)
我加一下

2023-03-27 07:09 UTC, trim21 requested changes

2023-03-27 07:09 UTC, trim21 commented on readme.md
> +```bash
```suggestion
```
```

2023-03-27 07:11 UTC, trim21 commented on internal/search/noop.go
> +func (n NoopClient) OnSubjectUpdate(_ context.Context, _ model.SubjectID) error {
你的golangci-lint版本不是v1.51.1吧？等我改一下lint规则

2023-03-27 07:12 UTC, kagaya85 commented on internal/search/noop.go
> +func (n NoopClient) OnSubjectUpdate(_ context.Context, _ model.SubjectID) error {
> 你的golangci-lint版本不是v1.51.1吧？等我改一下lint规则

我是1.52.2

2023-03-27 07:13 UTC, trim21 commented on readme.md
> +task test # Run mocked unit tests, need nothing.
啊，不小心弄错了233

2023-03-27 07:26 UTC, trim21 requested changes
写一下openapi文档

2023-03-27 07:31 UTC, trim21 commented
就测试和openapi这两个问题了

2023-03-27 15:16 UTC, kagaya85 commented
> 

done

2023-03-28 07:42 UTC, merged

2023-03-28 12:02 UTC, kagaya85 commented
Thanks for reviewing 🥰