feat(collection): Add POST/PUT method to create a subject collection if not exists
bangumi/server pull request #325
Opened 2023-04-10 12:53 UTC by RanKKI

see issue #324

---

就是在想 POST 如果到一个存在的 record 上，是应该 update 还是报错

2023-04-10 12:56 UTC, trim21 commented
update吧

2023-04-10 12:57 UTC, RanKKI commented
> update吧

Ok，现在的逻辑就是 update

2023-04-10 13:01 UTC, trim21 commented on internal/collections/infra/mysql_repo.go
> +		UserID:    userID,
ip呢

2023-04-10 13:06 UTC, RanKKI commented on internal/collections/infra/mysql_repo.go
> +		UserID:    userID,
后面 update 会把 ip 加进去，这里只建了个空 record

2023-04-10 13:09 UTC, trim21 commented
感觉提供的方法太多了点，实现起来也太复杂了。要不把patch改成可创建，然后只留一个patch方法算了。

2023-04-11 01:30 UTC, RanKKI commented
> 感觉提供的方法太多了点，实现起来也太复杂了。要不把patch改成可创建，然后只留一个patch方法算了。
> 
> 对大家都方便（）

:( 

是有一点点多啊， 但 patch 可以创建新资源， 有一丝奇怪。

我又想到， POST 和 PUT 理论上需要接受所有参数才对，不能有 null 值

2023-04-11 07:45 UTC, trim21 commented
你说的这两点我也是这么想的…

2023-04-11 08:52 UTC, trim21 commented
那不要加put方法了，被post已经完全覆盖了

2023-04-12 06:43 UTC, RanKKI commented
> Post 语义没put那么明确，支持部分字段应该也没什么问题。
> 
> 不过这样一来patch也被post完全覆盖了（）

🤔

这样吧，

不要 PUT，然后 POST 留着 （支持部分字段），PATCH 暂时不动，

PATCH 我想着说能新建，然后返回 201。但毕竟线上 API，还是不动比较合适。

2023-04-12 12:05 UTC, RanKKI commented
改好了。
( test 那个的 commit message 的 `the` 竟然写错位置了... 没发现 or2

2023-04-12 12:07 UTC, trim21 commented
无所谓的，我也不是按commit review的（）而且合并都是squash，也不会保留历史。

2023-04-12 12:37 UTC, trim21 requested changes

2023-04-12 12:37 UTC, trim21 commented on openapi/v0.yaml
> +      summary: 修改用户单个收藏
改一下

2023-04-12 12:38 UTC, trim21 commented on generated/proto/go/api/v1/timeline.pb.go
> -// 	protoc-gen-go v1.30.0
task install一下，然后重新生成一下。

2023-04-15 06:18 UTC, trim21 commented on internal/collections/infra/mysql_repo.go
> +		UserID:    userID,
不能等update完了一块写到数据库吗

2023-04-15 09:22 UTC, RanKKI commented on internal/collections/infra/mysql_repo.go
> +		UserID:    userID,
当时想的是，尽量不动之前的代码。

2023-04-16 20:13 UTC, trim21 commented on internal/collections/infra/mysql_repo.go
> +		UserID:    userID,
改改（

2023-04-24 04:15 UTC, merged