fix:missing subject type
bangumi/server pull request #352
Opened 2023-05-22 07:15 UTC by fiochen

[新增收藏API](https://bangumi.github.io/api/#/%E6%94%B6%E8%97%8F/postUserCollection)中，缺少了subject type的写入，会导致收藏列表相关功能获取不到条目

2023-05-22 13:35 UTC, RanKKI requested changes
修和补充一下测试用例吧～

2023-05-22 13:35 UTC, RanKKI commented on internal/collections/infra/mysql_repo.go
> +		Where(r.q.Subject.ID.Eq(subject)).Take()
这里只 Select `TypeID` 会不会好一些？ 毕竟其他属性都不用上

2023-05-22 13:35 UTC, RanKKI commented on internal/collections/infra/mysql_repo.go
> +func (r mysqlRepo) getSubjectType(ctx context.Context, subject model.SubjectID) (model.SubjectType, error) {
变量名字保持一致吧～ 用 `subjectID`

2023-05-22 14:29 UTC, fiochen commented on internal/collections/infra/mysql_repo.go
> +		Where(r.q.Subject.ID.Eq(subject)).Take()
在ctrl层里可以从缓存拿，dao里面调用不了。要不我在`updateOrCreateSubjectCollection`里加多个SubjectType的参数？

2023-05-22 14:47 UTC, fiochen commented on internal/collections/infra/mysql_repo.go
> +		Where(r.q.Subject.ID.Eq(subject)).Take()
> 看了下， 这里能从缓存拿 Subject 信息。可以参考 `update_subject_collection.go` 里的 `mayCreateTimeline`方法

在ctrl层里可以从缓存拿，dao里面调用不了。要不我在updateOrCreateSubjectCollection里加多个SubjectType的参数？

2023-05-23 02:55 UTC, RanKKI commented on internal/collections/infra/mysql_repo.go
> +		Where(r.q.Subject.ID.Eq(subject)).Take()
嗯嗯，或者可以传 subject 进去。

2023-05-23 04:11 UTC, fiochen commented
@RanKKI 重新提交了

2023-05-24 01:49 UTC, RanKKI approved these changes
看着没啥问题， 但这么传参，方法会越来越长吧 hh
是不是放在结构体里会好些 @trim21

2023-05-24 02:09 UTC, trim21 commented
现在这样也行， 看 @fiochen 有没有兴趣改。

2023-05-24 06:47 UTC, merged