feat: (revision) draft
bangumi/server pull request #48
Opened 2021-12-25 10:02 UTC by Sociosarbis

人物 & 角色编辑历史

2021-12-25 10:04 UTC, Trim21 commented
人物和角色分开两个PR吧

2021-12-25 10:27 UTC, Trim21 commented
PR描述里写一下各种响应的实际返回值？

2021-12-26 13:46 UTC, Trim21 commented
`prsn_infobox` 不解析了，返回原本的字符串就好了。

2021-12-27 15:56 UTC, Sociosarbis commented
今天`master` refactor了get_db，这种情况按以往经验PR是需要merge主分支的改动吗？

2021-12-27 23:03 UTC, Trim21 commented
> 今天`master` refactor了get_db，这种情况按以往经验`PR`是需要`merge`主分支的改动吗？

是的

2021-12-31 04:27 UTC, Trim21 requested changes

2022-01-05 16:12 UTC, Trim21 commented on pol/api/v0/revision.py
>      )
这里只有一个join条件，直接写一起吧

2022-01-08 10:51 UTC, Trim21 commented on pol/api/v0/models/creator.py
> -    username: str
抱歉，我之前理解错了这个 `username` 的含义，用户没有修改过 `username` 的情况下这个就是对应的 uid。能麻烦再修改一下吗，只返回 `username` 不返回 `id` 了

2022-01-08 14:05 UTC, merged