feat: add comment API
bangumi/server pull request #566
Opened 2024-05-27 13:46 UTC by L-time

为 Subject Post 和 Index Comment 增加了API与后端逻辑。

WIP:

1. 为剧集评论增加API
2. 增加吐槽箱与评分（顺带一提，我并未找到相关的数据库，可以的话能否准确告知一下）
3. 补充Mock测试（我还没找到mockey怎么生成……）
4. 文档

2024-05-27 13:49 UTC, L-time commented
顺便请求一下.可否告知一下关于Mock的具体流程，以前一直都是直接本地跑所以对于Mock的自动生成有一点没懂（

2024-05-27 13:56 UTC, trim21 commented
> * 补充Mock测试（我还没找到mockey怎么生成……）

用 [task](https://taskfile.dev/)

https://github.com/bangumi/server/blob/cedf8505505b878f5f4e97ce32a2c30320881ad0/Taskfile.yaml#L88-L91

2024-05-27 13:57 UTC, trim21 commented
吐槽箱就是条目收藏的评论字段

2024-05-27 15:16 UTC, trim21 commented
wip的话在标题里加上`[WIP]` 或者用draft

2024-05-27 16:31 UTC, L-time commented
> 吐槽箱就是条目收藏的评论字段

好的，明白了

2024-05-28 20:56 UTC, Him188 commented
这是 #526, 可以链接一下?

2024-06-02 13:06 UTC, L-time commented
@trim21 好了

2024-06-02 15:19 UTC, trim21 commented
暂时先不允许修改吐槽吧，这个还有用户权限控制的问题

2024-06-02 15:22 UTC, trim21 commented
先解决下冲突

2024-06-06 15:38 UTC, L-time commented
@trim21 lint 剩下的文件我都没有修改，这些警告我不确定是否需要解决

2024-06-06 15:41 UTC, trim21 commented
> @trim21 lint 剩下的文件我都没有修改，这些警告我不确定是否需要解决

报错的都是你改过的文件

2024-06-06 15:42 UTC, trim21 commented
![image](https://github.com/bangumi/server/assets/13553903/6f2e2675-f330-4e8f-a977-7f9e9ffcc54d)

2024-06-06 16:10 UTC, L-time commented
> ![image](https://private-user-images.githubusercontent.com/13553903/337335028-6f2e2675-f330-4e8f-a977-7f9e9ffcc54d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTA0MzYsIm5iZiI6MTcxNzY5MDEzNiwicGF0aCI6Ii8xMzU1MzkwMy8zMzczMzUwMjgtNmYyZTI2NzUtZjMzMC00ZThmLWE5NzctN2Y5ZTlmZmNjNTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE2MDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTRkM2NjYjk3NWJmOGM4ZDhlYmE2ZDk1NGM2YmI0ZGRhNWViODZmN2EyMzE0MzgwOGYwZGVjZGEyNzRjYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RHKwmoD20BIBDxMlfWJ7WJy2zdIa1DCL6TQPV2KtPK8)

修了，本地跑一遍fmt就交

2024-06-06 16:17 UTC, L-time commented
@trim21 好了

2024-06-06 19:14 UTC, trim21 requested changes

2024-06-06 19:14 UTC, trim21 commented on go.mod
> +	github.com/daixiang0/gci v0.13.4 // indirect
这个怎么变成依赖了，用golangci-lint

2024-06-06 19:16 UTC, trim21 commented on internal/index/mysql_repository_test.go
> -		Description: "Test Index",
这个不需要改吧

2024-06-06 22:59 UTC, trim21 commented on web/req/subject.go
> +type SubjectComment struct {
这是啥……

2024-06-06 23:00 UTC, trim21 commented on web/handler/subject/subject.go
> +	g.PUT("/subjects/:id/post", h.AddComment, mw.NeedLogin)
暂时先不允许添加评论，这个也涉及ACL

2024-06-06 23:01 UTC, trim21 commented on web/handler/index/index.go
> +		return errgo.Wrap(err, "failed to crea te a new index")
typo

2024-06-06 23:01 UTC, trim21 commented on web/handler/index/index.go
> +		return errgo.Wrap(err, "Field.CountSubjects")
这些为啥要改？

2024-06-06 23:02 UTC, trim21 commented on web/handler/index/comment.go
> +	offsetStr := c.QueryParam("offset")
有个util能解析公用的翻页参数的

2024-06-07 02:52 UTC, L-time commented on go.mod
> +	github.com/daixiang0/gci v0.13.4 // indirect
我本地出了点问题，不变成依赖没办法运行，稍后去掉

2024-06-07 02:53 UTC, L-time commented on internal/index/mysql_repository_test.go
> -		Description: "Test Index",
lint自动修改了，我没有动这些测试方法，我稍后改回去2

2024-06-07 02:54 UTC, L-time commented on web/handler/subject/subject.go
> +	g.PUT("/subjects/:id/post", h.AddComment, mw.NeedLogin)
好的，稍后把对应路由先去除

2024-06-07 02:54 UTC, L-time commented on web/handler/index/index.go
> +		return errgo.Wrap(err, "failed to crea te a new index")
XD，马上改

2024-06-07 02:54 UTC, L-time commented on web/handler/index/index.go
> +		return errgo.Wrap(err, "Field.CountSubjects")
如上
> lint自动修改了，我没有动这些测试方法，我稍后改回去2

2024-06-07 02:55 UTC, L-time commented on web/handler/index/comment.go
> +	offsetStr := c.QueryParam("offset")
收到，我稍后改正

2024-06-08 08:08 UTC, L-time commented
@trim21 可否开放一下``bangumi.chii_subject_posts`` ``bangumi.chii_ep_comments`` 这两个表？我需要写测试XD

2024-06-08 11:51 UTC, trim21 commented
啥叫开放一下，是dev-env里面没有吗？

2024-06-08 12:30 UTC, L-time commented
> 啥叫开放一下，dev-env里面没有？还是什么其他情况？

里面没有任何测试数据

2024-06-09 15:10 UTC, trim21 commented
> > > 啥叫开放一下，dev-env里面没有？还是什么其他情况？
> > 
> > 
> > 里面没有任何测试数据
> 
> 没有数据，我没办法测试get方法，所以我现在也不知道怎么写测试

等会我导出一下

2024-06-09 15:18 UTC, L-time commented
> > > > 啥叫开放一下，dev-env里面没有？还是什么其他情况？
> > > 
> > > 
> > > 里面没有任何测试数据
> > 
> > 没有数据，我没办法测试get方法，所以我现在也不知道怎么写测试
> 
> 等会我导出一下

好的，感谢您）

2024-06-09 22:24 UTC, Him188 commented on web/handler/subject/subject.go
> +	g.PUT("/subjects/:id/post", h.AddComment, mw.NeedLogin)
想顺便问一下 现在ACL基建有吗？是只需要加一条权限(和对应的ui) 就可以，还是完全没有ACL支持？

2024-06-14 18:16 UTC, L-time commented
> > > > > 啥叫开放一下，dev-env里面没有？还是什么其他情况？
> > > > 
> > > > 
> > > > 里面没有任何测试数据
> > > 
> > > 
> > > 没有数据，我没办法测试get方法，所以我现在也不知道怎么写测试
> > 
> > 
> > 等会我导出一下
> 
> 好的，感谢您）

询问一下好了嘛）

2024-06-16 07:28 UTC, trim21 commented
bangumi.chii_subject_posts 应该是条目讨论帖？

2024-06-17 09:31 UTC, L-time commented
> bangumi.chii_subject_posts 应该是条目讨论帖？

对的

2024-06-17 10:41 UTC, trim21 commented
> > bangumi.chii_subject_posts 应该是条目讨论帖？
> 
> 对的

你找个沙盒条目发点讨论贴吧？现在几个沙盒条目都没有讨论贴，没什么数据可导出（

2024-06-20 05:40 UTC, L-time commented
> > > bangumi.chii_subject_posts 应该是条目讨论帖？
> > 
> > 
> > 对的
> 
> 你找个沙盒条目发点讨论贴吧？现在几个沙盒条目都没有讨论贴，没什么数据可导出（

沙盒条目可以给个导航嘛（

2024-06-20 05:56 UTC, trim21 commented
> > > > bangumi.chii_subject_posts 应该是条目讨论帖？
> > > 
> > > 
> > > 对的
> > 
> > 
> > 你找个沙盒条目发点讨论贴吧？现在几个沙盒条目都没有讨论贴，没什么数据可导出（
> 
> 沙盒条目可以给个导航嘛（

https://bgm.tv/index/36778

2024-06-23 10:31 UTC, closed without merging