feat: relation between person and character
bangumi/server pull request #61
Opened 2021-12-28 06:19 UTC by MoguCloud

现实-虚拟人物关联
GET /v0/characters/{character_id}/persons 获取虚拟人物相关联的现实人物
GET /v0/persons/{person_id}/characters 获取现实人物相关联的虚拟人物

2021-12-28 06:21 UTC, Trim21 commented
写一下具体响应的例子

2021-12-28 06:29 UTC, Trim21 requested changes

2021-12-28 06:29 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
不是这个表，是 `chii_crt_cast_index`

2021-12-28 06:36 UTC, MoguCloud commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
直接查表`chii_crt_cast_index`，不用查表`chii_character`来判断`character_id`是否存在对吧？

2021-12-28 06:48 UTC, MoguCloud commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
不判断`character_id`是否存在的话，url里传入一个不存在的`character_id`会返回200, 空列表，而不是404

2021-12-28 06:49 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
不用去人物查关联的条目和人物。

2021-12-28 06:52 UTC, MoguCloud commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
那只要返回人物/角色关联的条目id和角色/人物id吗?

2021-12-28 06:53 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
类似于这个页面 https://bgm.tv/character/7251/add_related/person/anime

2021-12-28 06:55 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
大概类似于`RelatedSubject`+`RelatedPerson`/`RelatedCharacter`，去掉 `relation` 字段

2021-12-28 07:09 UTC, MoguCloud commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
那个链接我没有权限打开，看不到

2021-12-28 07:11 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
![image](https://user-images.githubusercontent.com/13553903/147538714-c70ac2f9-76b1-46c2-9e49-a4e47dd3bd99.png)

2021-12-28 07:16 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
（还是要判断一下对应的角色/人物是否存在的

2021-12-28 07:20 UTC, MoguCloud commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
那我定义的接口响应结果有没有问题呀？表`chii_crt_cast_index`只有id，是不用join，在模型里定义`relationship`去查吗？

2021-12-28 07:25 UTC, Trim21 commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
我是说options这一行是没有用的，额外多了两个数据库查，而且返回的数据也没有用。

2021-12-28 07:26 UTC, MoguCloud commented on pol/api/v0/character.py
> +            sa.selectinload(ChiiCharacter.subjects).joinedload(
我瞎了抱歉qwq

2021-12-28 07:30 UTC, Trim21 commented on pol/api/v0/person.py
> +        .where(ChiiPerson.prsn_id == person_id)
没检查prsn_ban

2021-12-28 07:39 UTC, Trim21 commented
不要force push，影响review…

2021-12-28 08:30 UTC, Trim21 requested changes

2021-12-28 08:46 UTC, MoguCloud commented on pol/api/v0/character.py
> +    if character.crt_redirect:
已修改

2021-12-28 08:52 UTC, merged

2022-01-16 04:20 UTC, Trim21 commented
在吗，能不能看一下这个issue（ 
https://togithub.com/bangumi/server/issues/87